from pynput.keyboard import Key, Controller
import time
k = Controller()
column= input("Enter column letter: ")
rowstart = int(input("Enter starting row number: "))
rowend = int(input("Enter ending row number: "))
interval = int(input("Enter blocksize: "))
r = 1
destcolumn = chr(ord(column)+2)
print('Starting in 5 seconds [alt tab to your excel sheet]')
time.sleep(5)
for i in range(interval + rowstart - 1, rowend, interval):
    k.press(Key.ctrl)
    k.type('g')
    k.release(Key.ctrl)
    k.type(f'{column}{i}:{column}{i-interval+1}')
    k.type('\n')
    k.press(Key.ctrl)
    k.type('c')
    k.release(Key.ctrl)
    k.press(Key.ctrl)
    k.type('g')
    k.release(Key.ctrl)
    k.type(f'{destcolumn}{r}')
    k.press(Key.alt)
    k.type('e')
    k.release(Key.alt)
    k.type('s')
    k.press(Key.alt)
    k.type('e')
    k.release(Key.alt)
    k.type('\n')
print("done")